name: jackpot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  brasil_fields: ^1.15.0
  camera: ^0.11.1
  curl_logger_dio_interceptor: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  easy_rich_text: ^2.2.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_mlkit_face_detection: ^0.13.1
  gradient_widgets_plus: ^1.0.0
  http: ^1.3.0
  image: ^4.5.4
  intl: ^0.19.0
  localization: ^2.1.1
  lottie: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  pagseguro_card_encrypt: ^1.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdfviewer: ^29.1.40
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
    - assets/animations/gifs/
    - assets/images/
    - assets/json/
    - assets/docs/
    - lib/i18n/i18n/
